# Generated by Django 4.2.3 on 2023-08-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=122)),
                ('category', models.CharField(max_length=122)),
                ('image', models.TextField()),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
