# Generated by Django 4.2.3 on 2023-08-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='image',
            field=models.ImageField(upload_to='home/images'),
        ),
    ]
